// LOCALHOST
### Get main
GET http://localhost:3000


### Get inventory items
GET http://localhost:3000/inventory


### POST / Create users
POST http://localhost:3000/inventory HTTP/1.1
content-type: application/json

{
    "email":"aWeaver@test.com",
    "username":"Brown",
    "name":"Rebekah",
    "ipaddress":"94.121.168.53"
}

### GET Single Item
GET http://localhost:3000/inventory/6516c544e607fc26fbcf1998


### PUT / Update Item
PUT http://localhost:3000/inventory/6516c544e607fc26fbcf1998 HTTP/1.1
content-type: application/json

{
    "firstName":"Maxine",
    "lastName":"Maxwell",
    "email":"mMaxwell@test.com",
    "favoriteColor":"Blue",
    "birthday":"09/09/1988"
}

### Delete Item
DELETE http://localhost:3000/inventory/6516b9266142857a3dcfb200

### Get all suppliers
GET http://localhost:3000/supplier

### Create one supplier
POST http://localhost:3000/supplier HTTP/1.1
Content-Type: application/json

{
    "supplier": "post",
    "address": "post",
    "phone": "123-4567",
    "url": "123.com"
}

### Get one supplier by id
GET http://localhost:3000/supplier/6514fef513ad481905b14c33

### update one supplier
PUT http://localhost:3000/supplier/6516bb3ff527655a357c3e0f HTTP/1.1
Content-Type: application/json

{
    "supplier": "put",
    "address": "put",
    "phone": "123-4567",
    "url": "test.com"
}

### Delete one supplier
DELETE http://localhost:3000/supplier/6516bb95f527655a357c3e10